### ISSUE TITLE
docutils version mismatch?

### ISSUE THREAD

**Issue by luiguip** [JaDogg/pydoro#110]
Hi, when I run:
```console
python -m venv env
source env/bin/activate
pip install -r dev_requirements.txt
```

I receive this error.
```console
ERROR: docutils-stubs 0.0.21 has requirement docutils==0.14, but you'll have docutils 0.16 which is incompatible.
```
am I doing something wrong?

**Comment by JaDogg** [comment]
That is an issue 🙃

**Comment by JaDogg** [comment]
@luiguip can you try to run it on on a tagged release?

**Comment by luiguip** [comment]
Still happens on tag 0.2.1, I searched for the docutils-stubs and in it's dependences it requires the docutils 0.14.
https://github.com/tk0miya/docutils-stubs/blob/master/setup.py
I did fast tests yesterday and It was okay but wasn't a proper testing. Before change it, a good ideia is develop tests to make sure it won't break.

**Comment by JaDogg** [comment]
Yes need to do some CI https://github.com/JaDogg/pydoro/issues/94. I didn't had any time to do it. 😢

**Comment by JaDogg** [comment]
As far as I remember, docutils come with some dependencies for building and publishing to PyPI. So to run pydoro you don't need it

**Comment by JaDogg** [comment]
Added a github action. Let's see if it solves this problem for us :)

**Comment by JaDogg** [comment]
Fixed
