### ISSUE TITLE
Create F1 dialog to show current configured shortcuts :) 

### ISSUE THREAD

**Issue by JaDogg** [JaDogg/pydoro#127]
Display a help window with current configured keyboard shortcuts.

See if <kbd>F1</kbd> can be used as the key. if not use something like <kbd>?</kbd>

`UserInterface` class need to updated to support the new window. notice that `Configuration` object is passed to this class. This has the information that needs to be displayed.

Project docs are in wiki - https://github.com/JaDogg/pydoro/wiki

**Comment by kana800** [comment]
Hey there; 👋🏽 Is anyone working on this feature?
I am interested on working on it

**Comment by JaDogg** [comment]
@kana800 Awesome, No one is working on the issue at the moment. :) 👍🏽 I have added few ideas to get you started to the above issue description.

**Comment by kana800** [comment]
@JaDogg Hey there before I proceed; do you want the help window to be a separate window or something integrated to the pydoro UI
![image](https://user-images.githubusercontent.com/64830745/191929336-72b82678-ac84-4a22-8c07-6f5913ae6f05.png)

![image](https://user-images.githubusercontent.com/64830745/191929596-19af6157-29bd-4d91-8641-45c2e2caa439.png)

**Comment by JaDogg** [comment]
@kana800 I like the first one which you already got working. If you can remove the background colour / have the same background colour it would be better so it remains a bit consistent. 

Put an OK button in help window.

**Comment by JaDogg** [comment]
I have also assigned the ticket to you. So it is clear that you are working on it 
![FeelMeThinkAboutItGIF](https://user-images.githubusercontent.com/498642/192025956-3c44d450-324d-400f-bb84-497189cf238e.gif)

**Comment by kana800** [comment]
> @kana800 I like the first one which you already got working. If you can remove the background colour / have the same background colour it would be better so it remains a bit consistent.

Hey @JaDogg !
I just did some research and figured out the first method is bit harder to implement (idk whether its doable) .

> The reason is that the pop-up dialog should become part of the application layout in order to be displayed. There can be only one application running, so you have to add it to your main application. (The 'dialogs' shortcuts won't do that.) Further, the dialog shortcuts starts the event loop, this doesn't work in the middle of a running application, and causes the error you had. [link ](https://github.com/prompt-toolkit/python-prompt-toolkit/issues/666#issuecomment-404276117)

So I have decided to use a simple [conditional container](https://python-prompt-toolkit.readthedocs.io/en/master/pages/reference.html?highlight=conditional%20container#prompt_toolkit.layout.ConditionalContainer).  Let me know if you are okay with this.

https://user-images.githubusercontent.com/64830745/192106011-20cbf06f-d406-4a32-bd77-8914e4e72f21.mp4



Let me know if you prefer any specific styling; I will make a pull request later.

Cheers!

**Comment by JaDogg** [comment]
This looks good. 👍🏽 Can you add a text saying `Help` above the shortcuts. This way the help section has a title.

Add your name to the README when you are sending the PR. Good stuff. 👍🏽

**Comment by JaDogg** [comment]
Merged. Closing this ticket. 👍🏽👍🏽
