### ISSUE TITLE
No animation/Silent mode

### ISSUE THREAD

**Issue by supermitch** [JaDogg/pydoro#13]
If I run Pydoro in a visible iTerm pane, the timer animation is distracting. Perhaps having a "silent mode" would be nice, just animate when done, so as to break distraction less.

**Comment by JaDogg** [comment]
@supermitch do you mean the progress animation or the remaining time?

**Comment by supermitch** [comment]
I was thinking both, but the progress animation is more distracting than the timer.

Perhaps the timer could just down down the minutes instead of the seconds? Then it would be much less distracting, but you'd still know how much time was left. (Although, I think the goal is to get into the zone and not be watching the time.) Could be two separate issues.

**Comment by gmelodie** [comment]
Hi there, can I work on this? If so, how would the silent mode be selected?

**Comment by JaDogg** [comment]
@gmelodie use a command line arg such as `pydoro --silent` for now. 👍
