### ISSUE TITLE
Availability for small window in phone

### ISSUE THREAD

**Issue by wi24rd** [JaDogg/pydoro#14]
I want to use this program in termux, however it is just saying "Window too small..."

**Comment by JaDogg** [comment]
Can you tell me the phone resolution? And roughly what kind of terminal `width x height` you have in termux (in characters) ? I was able to run it using PyDroid.

**Comment by JaDogg** [comment]
@wi24rd any idea?

**Comment by wi24rd** [comment]
![A5FDB3148C46C58DA426B92DEDD2F000](https://user-images.githubusercontent.com/14029004/60946922-06cfad80-a322-11e9-9ecf-e7e9e9b364f4.jpg)

That is my specification.
It acts like what I say above by default no matter landscape or portrait.
I just didn't use termux for a long time and forgot that I can drag and scroll it's scale.
After that, it is fine.
Sorry to trouble you.

**Comment by wi24rd** [comment]
But if it can be more responsive, it'd be better.
