### ISSUE TITLE
Fix build script

### ISSUE THREAD

**Issue by JaDogg** [JaDogg/pydoro#147]

**Comment by saikirankv** [comment]
@JaDogg  I would like to work on this. Can you provide more details?

**Comment by JaDogg** [comment]
@saikirankv Please check the pull requests from the bot. They seem to be failing for some reason. This is to figure it out how to fix it and send a pull request for GitHub action. :)

**Comment by saikirankv** [comment]
Got it, found the issue need sometime to submit a valid fix.
