### ISSUE TITLE
Introduce a config file for keybindings, and other features

### ISSUE THREAD

**Issue by JaDogg** [JaDogg/pydoro#15]
There is a recent pull request https://github.com/JaDogg/pydoro/pull/12  for introducing a config file. However I want to modify it and introduce an `.ini` as a config file so people don't need to edit code to change things. 

## Where to look for config file
1) Look in the location set in `PYDORO_CONFIG_FILE`
2) Look in `~/.pydoro.ini`
3) Look in `current dir/.pydoro.ini`

## Config format
```ini
[keys]
navigate_left = ["left", "s-tab"]

[animation]
no_seconds = False # Only show minutes if this is True.
no_progress = False # Does not animate the indefinite progress bar.

[time]
work_minutes = 25
sbreak_minutes =  5
lbreak_minutes = 15
```

**Comment by gmelodie** [comment]
Can you specify exactly which options should be configured by this file? Also, can I work on this? :smiley:

**Comment by JaDogg** [comment]
@gmelodie Sure and Thank you again 🤗. 
Please add options you created in other merge, `--emoji` option. 
`no_seconds.` thing is not needed anymore. Other options are keyboard shortcuts + time chunks.

**Comment by gmelodie** [comment]
What do you mean with `--emoji` option?

**Comment by JaDogg** [comment]
@gmelodie I've made a release with configuration feature 😎 Thank you for contributing. You rock 🤘

**Comment by gmelodie** [comment]
@JaDogg I'm sorry I haven't had much time to work on the project lately, been caught up on some stuff. Thanks for allowing me to work on this, will give this a try anytime now :)
