### ISSUE TITLE
Add support for cmd/shell execution.

### ISSUE THREAD

**Issue by Liupold** [JaDogg/pydoro#269]
While working or taking a break it would be nice if it can automatically trigger system events. For example, turning the internet on/off or blocking/unblocking a few sites or even as simple as turning system sound on or off.

This is probably not that difficult to implement and a few lines in the `general` section of `.ini` file will do.
```
...
[general]
work_start_cmd  = "echo 'WORK'"
work_end_cmd  = "echo 'TAKE A BREAK'"
...
```
This can also be used to send notifications.

**Comment by JaDogg** [comment]
merged
