### ISSUE TITLE
[FEAT] Would itbe possible to make it so you can change the sound the timer makes?

### ISSUE THREAD

**Issue by j-barnak** [JaDogg/pydoro#287]
**Is your feature request related to a problem? Please describe.**
The sound for the alarm is harsh and piercing. Could you add a feature that could customize the sound?

**Describe the solution you'd like**
Within the .ini file, you could customize the sound.

**Describe alternatives you've considered**
I just mute the sound

**Additional context**

**Comment by JaDogg** [comment]
Currently as a workaround you can use `--audio-file` argument to change the bell sound. However it is not there in the configuration. 

```
pydoro --audio-file yourfile.wav
```

`https://github.com/JaDogg/pydoro/blob/develop/pydoro/pydoro_core/config.py` need to be changed to support loading the alternative sound from `.ini` also. We can keep that optional.

**Comment by JaDogg** [comment]
I added this feature.

Now in INI you can do

```
[General]
audio_file = path/file.wav
```

**Comment by JaDogg** [comment]
Documentation added for wiki as well -> https://github.com/JaDogg/pydoro/wiki

**Comment by JaDogg** [comment]
You need to install from the git repo to get it working. :) Until I do a release. I'll do that later (●'◡'●)

**Comment by j-barnak** [comment]
To install from the repo, do you just clone the repo and then run setup.py? How would I run it if I already have the program already installed via pip?

**Comment by JaDogg** [comment]
Try 
1) `pip uninstall pydoro` or `pip uninstall "pydoro[audio]"` based on how you installed it
2) `pip install git+https://github.com/JaDogg/pydoro.git`
