### ISSUE TITLE
[BUG] Custom audio for alarm does not work

### ISSUE THREAD

**Issue by j-barnak** [JaDogg/pydoro#288]
**Describe the bug**
When I specify the the .wav file within the INI, the sound does not get played

**To Reproduce**
Set up the INI file so that it's the following:
```
[General]
no_clock = False
no_sound = True
emoji = False
; Set a file here to play this instead of default bell sound (Optional) 
audio_file = /home/jared/Sounds/Hummingbird-SoundBible.com-623295865.wav

[Time]
tomatoes_per_set = 4
work_minutes = 1
small_break_minutes = 5
long_break_minutes = 15
alarm_seconds = 5

[KeyBindings]
focus_previous = s-tab,left,h,j
focus_next = tab,right,l,k
exit_clicked = q
start = s
pause = p
reset = r
reset_all = a
```

1. Uninstall the pip package via `pip uninstall 'pydoro[audio]`
2. Build using `python3 ./setup.py build`
3. Install using `python3 ./setup.py install`
4. Run using `python pydoro/pydoro_tui.py`

**Expected behavior**
I expect the humming bird sound to play after the timer ends

**Desktop (please complete the following information):**
 - Linux Mint 21 "Vanessa"

**Comment by JaDogg** [comment]
You havent installed audio it seems. Try installing `pygame` also or `"pycairo>=1.18.1"` and 
`"PyGObject>=3.32.1"`

**Comment by j-barnak** [comment]
I have installed pygame via `sudo apt-get install python3-pygame`  
`pycairo` and `PyGObject` is installed via `pip3 install pycairo` and `pip3 install PyGObject`
`pycairo` is at `3.20.1`
`PyGObject` is at `3.42.1`

Still does not work

**Comment by JaDogg** [comment]
```
[General]
no_clock = False
no_sound = True ; <<<<<<<<<<<<<<<<--- is this set to true?
emoji = False
; Set a file here to play this instead of default bell sound (Optional) 
audio_file = /home/jared/Sounds/Hummingbird-SoundBible.com-623295865.wav
```

set it to False

**Comment by j-barnak** [comment]
Yes, this works now... sort of. The sound plays at the beginning after I press start as well.

**Comment by JaDogg** [comment]
Yes it is set to play at start, so you do not need to wait to hear the sound haha!

**Comment by j-barnak** [comment]
So, will this change with the release? Thanks for the hasty replies!

**Comment by JaDogg** [comment]
yes.. too lazy to do a release today... 🦥

**Comment by j-barnak** [comment]
Alright! Could you ping me when the release is out? Or is there someway to know. I'm not too familiar with pip

**Comment by JaDogg** [comment]
Press watch button in github.

**Comment by j-barnak** [comment]
I was notified on github. Is the release ready? 
Sorry for the pestering, but I really love this app!

**Comment by JaDogg** [comment]
Not yet. I'm waiting to see if I get a PR for another issue, you can watch just releases so you do not get all updates. I'll probably do it when I get  a holiday in few weeks.

**Comment by JaDogg** [comment]
@j-barnak I have done a release for `0.2.3` with new audio config support.

**Comment by j-barnak** [comment]
It works from the `pip install pydoro[audio] --upgrade`, but sound is played in the beginning. Is this intentional?

**Comment by JaDogg** [comment]
> Yes it is set to play at start, so you do not need to wait to hear the sound haha!

yes it is the intended behaviour
