### ISSUE TITLE
[BUG] AttributeError: 'NoneType' object has no attribute 'props'

### ISSUE THREAD

**Issue by kz6fittycent** [JaDogg/pydoro#293]
**Describe the bug**
pydoro fails to play sound(s). Please see "Additional Context". 

**To Reproduce**
1. `pydoro --audio-check`
2. Press Enter '....'
3. See error
```
Traceback (most recent call last):
  File "/snap/pydoro/44/bin/pydoro", line 8, in <module>
    sys.exit(main())
  File "/snap/pydoro/44/lib/python3.8/site-packages/pydoro/pydoro_tui.py", line 130, in main
    sound.play(in_app_path("b15.wav"), block=True)
  File "/snap/pydoro/44/lib/python3.8/site-packages/pydoro/pydoro_core/sound.py", line 135, in _play_sound_nix
    _play_sound_nix_blocking(sound)
  File "/snap/pydoro/44/lib/python3.8/site-packages/pydoro/pydoro_core/sound.py", line 114, in _play_sound_nix_blocking
    playbin.props.uri = "file://" + pathname2url(os.path.abspath(sound))
AttributeError: 'NoneType' object has no attribute 'props'

```
**Expected behavior**
I expected pydoro to play it's default sound or one that I chose (.wav). 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Pop!_OS 
 - Version 22.04

**Additional context**
Please note, I am working on a snap for pydoro - so put your container hat on. :)

**Comment by JaDogg** [comment]
Try to add the `pygame` package to it as well.. See how they have done here. I do not know much about `snap`. Good luck. :) 

https://github.com/Joker2770/awesome-pygames/blob/main/snap/snapcraft.yaml

**Comment by kz6fittycent** [comment]
Thanks for responding (wow that was fast!). I have the following packages in both the `build/stage` packages:
```
    build-packages:
      - python3
      - python3-gi
      - python3-pip
      - python3-pygame
      - python3-gst-1.0      
      
    stage-packages:
      - python3
      - python3-gi
      - python3-pygame
      - python3-gst-1.0
      - gstreamer1.0-libav
     
```

That same error shows up in several places on the internet and so I added gstreamer in stage to see if would pick it up. I've also opened a thread [here](https://forum.snapcraft.io/t/attributeerror-nonetype-object-has-no-attribute-prop/31836).

In fact, once I got the snap working, I intended to do a PR so others could reference the snap - which I'm happy to maintain since it automatically builds when you perform commits to your repo.

**Comment by JaDogg** [comment]
Error you pasted above should not happen if pydoro can successfully import `pygame`.
Try below bit of code and see if you can get any sound to play first.

```python
from pygame import mixer
import time

def pygame_sound_check(sound):
    mixer.init()
    mixer.music.load(sound)
    mixer.music.play()

    while mixer.music.get_busy():
        time.sleep(0.1)

if __name__ == "__main__":
    pygame_sound_check("/path/soundfile.wav")
```

**Comment by kz6fittycent** [comment]
Hey I figured it out!

Now I have a new error... :P

`pygame.error: No available audio device`

I think I know what this would be. I'll go ahead and close this issue and thanks again for helping!

**Comment by kz6fittycent** [comment]
Hey, @JaDogg  just an FYI

It turns out that Pop!_OS may be the real trouble-maker here. 

They use `/etc/pop-os/os-release` instead of `/etc/os/release` like everyone else. The snap works fine on other distros.
