### ISSUE TITLE
Additional keybindings

### ISSUE THREAD

**Issue by supermitch** [JaDogg/pydoro#3]
Nice project. An idea for enhancement:

* [x] Vim keybindings: `h` for left and `l` for right, synonyms for `tab` and `shift + tab`, respectively.
* [x] Shortcut keybindings: `(S)tart`, `(P)ause`, `(R)eset`, `Reset (A)ll`, `(E)xit`

**Comment by JaDogg** [comment]
I recently got left`<-` and right`->`, in a pull request. Is that enough for you?

**Comment by JaDogg** [comment]
I modified @Requiem's change to support <kbd>h</kbd> and <kbd>l</kbd> too.

**Comment by JaDogg** [comment]
Now in develop

**Comment by JaDogg** [comment]
@supermitch I'm marking this issue as closed. You can now use any key binding you like.
