### ISSUE TITLE
[ALSA lib pcm.c] strange characters appears after starting pydoro

### ISSUE THREAD

**Issue by Zead-Ashraf** [JaDogg/pydoro#316]
after I start a pomodoro session some strange charachters overrides the terminal

![2023-08-10_18-46](https://github.com/JaDogg/pydoro/assets/80642288/82f3b564-3cb9-4975-b1b0-85393694c808)

 - OS: Linux Debian
 - Version 12
 - (DWM) as a window manger

Note: it doesn't appear just after I execute the program, it works for a while very good, then this strange things happens

**Comment by JaDogg** [comment]
I think this has to do with how you have installed audio drivers. Try installing pygame in same virtual environment as the application.

Try with `--no-sound` and see if that fixes it. Also try installing pygame in same virtual environment and see if that fixes the issue for you.
