### ISSUE TITLE
No module pydoro_core tomato

### ISSUE THREAD

**Issue by DenGodunov** [JaDogg/pydoro#4]
No module pydoro_core tomato
![MINGW64cUsersdenisDesktop](https://user-images.githubusercontent.com/7568117/59909939-89e39f00-9419-11e9-963e-24102eb654d9.jpg)

**Comment by JaDogg** [comment]
@DenGodunov It doesn't support 2.7, you are able to however install it because I made a mistake in `setup.py` 😭
