### ISSUE TITLE
ImportError: No module named pydoro_core.tomato

### ISSUE THREAD

**Issue by binishjoshi** [JaDogg/pydoro#52]
I tired it running on Ubuntu 19.04. 
`pip3 install pydoro`
`pip3 install pydoro[audio]`
`pydoro`
Then I got this:

> ImportError: No module named pydoro_core.tomato

**Comment by JaDogg** [comment]
Can you try uninstalling both and just installing `pydoro[audio]` I think might have installed it twice.

**Comment by binishjoshi** [comment]
Thanks, it's working now
