### ISSUE TITLE
Support for notification daemon

### ISSUE THREAD

**Issue by UddipakBhuyan** [JaDogg/pydoro#53]
Is it possible to implement a system to send a notification after the timer counts to zero using notification daemon like _dunst_.
Also is the program suppose to play a sound when the timer finishes?

**Comment by JaDogg** [comment]
Program is supposed to play a sound. Although there is a change to make it optional happening already. 🤗

I'm not sure about the dunst. Can you explain what kind of advantages we have for using it?

**Comment by UddipakBhuyan** [comment]
The sound is not working in my case. Is there any further need for configuration to get the sound working after installing with
``pip install pydoro[audio]``

A use case of a dunst like notification is when someone would like a visual notification instead of a aural notification in case of silent environment like a library. If one wants to switch off the sound, he would require some visual information of when the timer finishes.

**Comment by JaDogg** [comment]
What is the OS / Python version you are using? 
**dunst** sound like an interesting idea.

**Comment by UddipakBhuyan** [comment]
OS: Arch Linux (5.3.8-arch1-1 kernel) with i3 window manager
Python Version: 3.7.4

**Comment by JaDogg** [comment]
Probably some issue is happening that's silenced 😢 will need to figure out a way to troubleshoot audio. One way to do it by default supress errors and have a custom parameter to test audio and exit.

**Comment by UddipakBhuyan** [comment]
Manual installation didn't help.

**Comment by UddipakBhuyan** [comment]
The sound issue is solved. It was probably a dependency issue of GStreamers. Installing the gst-plugins-bad package from arch repository installed the following packages

which seems to fixed it. I am listing the packages in case it might help you to troubleshoot sound issue with linux. Thanks for the help
