### ISSUE TITLE
Failed to build wheel for pycairo

### ISSUE THREAD

**Issue by binishjoshi** [JaDogg/pydoro#60]
During installation of audio dependencies on Kubuntu 19.10 using 

> pip3 install pydoro[audio]

Package cairo was not found in the pkg-config search path.
  Perhaps you should add the directory containing `cairo.pc'
  to the PKG_CONFIG_PATH environment variable
  No package 'cairo' found
  Command '['pkg-config', '--print-errors', '--exists', 'cairo >= 1.13.1']' returned non-zero exit status 1.
  
  ----------------------------------------
  Failed building wheel for pycairo

**Comment by JaDogg** [comment]
You might need to follow installation mentioned here: https://pygobject.readthedocs.io/en/latest/getting_started.html#ubuntu-logo-ubuntu-debian-logo-debian

**Comment by binishjoshi** [comment]
pip3 install pydoro[audio] worked but the sound doesn't come

**Comment by JaDogg** [comment]
install https://pygobject.readthedocs.io/en/latest/getting_started.html#ubuntu-logo-ubuntu-debian-logo-debian then uninstall and install `pydoro[audio]`

**Comment by binishjoshi** [comment]
I did that, still audio doesn't come.

**Comment by JaDogg** [comment]
Do you still get the package cairo not found after installing pygobject?

**Comment by binishjoshi** [comment]
Everything installed fine, just the sound isn't coming.

**Comment by JaDogg** [comment]
We should look into creating a way to test audio.. 🤔 This has happened to few people before but they sorted it.

**Comment by binishjoshi** [comment]
Okay, sure.

**Comment by JaDogg** [comment]
Created a new `--audio-check` argument that should show error messages
