### ISSUE TITLE
Colour ASCII tomato in green and red

### ISSUE THREAD

**Issue by JaDogg** [JaDogg/pydoro#7]
Leaves - green
Tomato - red

**Comment by JaDogg** [comment]
Done

**Comment by ulgens** [comment]
@JaDogg If you can mention the issue in PR, it would be easier to follow :slightly_smiling_face:

**Comment by JaDogg** [comment]
@ulgens Good idea. I've just pushed to master as a bad person 😞.

**Comment by JaDogg** [comment]
Commit: 46707e743e6a54dc818804b60b64736ed3205d16
