### ISSUE TITLE
No match for pip install pydoro[audio]

### ISSUE THREAD

**Issue by supermitch** [JaDogg/pydoro#92]
```
$ pip install pydoro[audio]
> no matches found: pydoro[audio]
```

- MacOS Mojave 10.14.6
- Successfully installed pip-20.0.2
- Python 3.7.2

**Comment by JaDogg** [comment]
@supermitch can you try to install it like this `pip install pydoro[audio]`

**Comment by supermitch** [comment]
That worked, in single quotes. Perhaps just an update to the README in the meantime, then. Thank you.
